### ISSUE TITLE
transfer to tc39-transfer

### ISSUE THREAD

**Issue by ljharb** [hax/proposal-raw-string-literals#3]
Hi! Stage 1 proposals are required to be in the TC39 github org. It'd be great if you could transfer this to the tc39-transfer org, and then I can bounce it into TC39.

**Comment by hax** [comment]
Sure. One thing I am not sure is whether I need to rename the proposal before transfer? In previous meeting, it seems some delegates don't like current "raw string literals" name.

**Comment by ljharb** [comment]
That would be ideal, but it can be done later too, nbd.

**Comment by ljharb** [comment]
thanks!
